# Generated by Django 3.2.4 on 2021-06-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_department'),
        ('userprofile', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='designation.department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='designation.designation'),
        ),
    ]
